# Generated by Django 3.0.8 on 2020-10-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_like_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='target',
            new_name='post',
        ),
    ]
